repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # only idsplay messages
            "-sn", # don`t display the score
            "--rcfile-.pylintrc", # link to my config file
            "--load-plugins=pylint.extensions.docparams", # load an extension
          ]